- task: SSH@0
  displayName: "Stop running containers"
  inputs:
    sshEndpoint: $(sshEndpoint)
    runOptions: "commands"
    commands: |
      docker stop backend-container || true
      docker stop frontend-container || true
      docker rm backend-container || true
      docker rm frontend-container || true

- task: SSH@0
  displayName: "Pull Docker Hub images"
  inputs:
    sshEndpoint: $(sshEndpoint)
    runOptions: "commands"
    commands: |
      docker pull $(dockerHubBackend):$(dockerTag)
      docker pull $(dockerHubFrontend):$(dockerTag)

- task: SSH@0
  displayName: "Run containers"
  inputs:
    sshEndpoint: $(sshEndpoint)
    runOptions: "commands"
    commands: |
      docker run -d --name backend-container -p 5000:5000 $(dockerHubBackend):$(dockerTag)
      docker run -d --name frontend-container -p 3000:3000 $(dockerHubFrontend):$(dockerTag)
